# Generated by Django 5.1.7 on 2025-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
