# Generated by Django 5.1.7 on 2025-08-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_max_stock_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_stock_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_stock_threshold',
        ),
    ]
