# Generated by Django 5.1.7 on 2025-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('RETIRADA', 'Pickup'), ('ENTREGA', 'Delivery')], max_length=8, null=True),
        ),
    ]
